CREATE TABLE dbo.ZKUsers (
    UserId VARCHAR(9) NOT NULL PRIMARY KEY,
    Name NVARCHAR(23) NOT NULL,
    Role VARCHAR(16) NOT NULL DEFAULT 'USER_DEFAULT',
    DevicePassword VARCHAR(8) NOT NULL DEFAULT '',
    CardNo BIGINT NOT NULL,
    Enabled BIT NOT NULL DEFAULT 1,
    GroupId TINYINT NOT NULL DEFAULT 0
);
CREATE TABLE dbo.ZKFingerprints (
    UserId VARCHAR(9) NOT NULL,
    FingerIndex TINYINT NOT NULL,
    Template VARBINARY(MAX) NOT NULL,
    PRIMARY KEY (UserId, FingerIndex),
    FOREIGN KEY (UserId) REFERENCES dbo.ZKUsers(UserId) ON DELETE CASCADE
);
CREATE TABLE dbo.ZkDevices (
    DeviceId INT NOT NULL PRIMARY KEY,
    DeviceName NVARCHAR(50) NOT NULL,
    DeviceIP VARCHAR(15) NOT NULL,
    DevicePort INT NOT NULL DEFAULT 4370,
    DeviceType VARCHAR(20) NOT NULL DEFAULT 'ZK',
    DeviceCmKey VARCHAR(32) NOT NULL DEFAULT '0',
    Location NVARCHAR(100) NULL
);